/*
 * palette4bootstrap - A netbeans palette plugin for the Bootstrap
 * Copyright (c) 2017-2018 Tauquir Ahmed (tauquirahmed93@gmail.com)
 * Licensed under the MIT License.
 */
package org.tauquir.palette4bootstrap.items;

import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.util.NbBundle;

public class BlankPageCustomizer extends javax.swing.JPanel {

    private Dialog dialog = null;
    private DialogDescriptor descriptor = null;
    private boolean dialogOK = false;

    private final BlankPage page;

    /**
     * Creates new form PAGECustomizer
     */
    public BlankPageCustomizer(BlankPage page) {
        this.page = page;

        initComponents();
    }

    public boolean showDialog() {
        dialogOK = false;
        descriptor = new DialogDescriptor(this, NbBundle.getMessage(BlankPageCustomizer.class, "Customizer.InsertPrefix")
                + " " + NbBundle.getMessage(BlankPageCustomizer.class, "UI.BLANKPAGE.NAME"), true,
                DialogDescriptor.OK_CANCEL_OPTION, DialogDescriptor.OK_OPTION,
                new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (descriptor.getValue().equals(DialogDescriptor.OK_OPTION)) {
                    evaluateInput();
                    dialogOK = true;
                }
                dialog.dispose();
            }
        });
        dialog = DialogDisplayer.getDefault().createDialog(descriptor);
        dialog.setResizable(false);
        dialog.setVisible(true);
        return dialogOK;
    }

    private void evaluateInput() {
        page.setPageTitle(jTitleField.getText());
        page.setBootstrapCSS(jMainCSS.getText());
        page.setjQueryJS(jJQueryJS.getText());
        page.setBootstrapJS(jMainJS.getText());
        page.setBootstrapThemeCSS(jThemeCSS.getText());
        page.setContainerType((jAddContainer.isSelected()) ? String.valueOf(jContainerClass.getSelectedItem()) : "");
        page.setAddIEsupport(jSupportOldIE.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTitleField = new javax.swing.JTextField();
        jMainCSS = new javax.swing.JTextField();
        jJQueryJS = new javax.swing.JTextField();
        jMainJS = new javax.swing.JTextField();
        jThemeCSS = new javax.swing.JTextField();
        jSupportOldIE = new javax.swing.JCheckBox();
        jAddContainer = new javax.swing.JCheckBox();
        jContainerClass = new javax.swing.JComboBox<>();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jLabel1.text")); // NOI18N
        jLabel1.setToolTipText(org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jTitleField.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jLabel2.text")); // NOI18N
        jLabel2.setToolTipText(org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jMainCSS.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jLabel3.text")); // NOI18N
        jLabel3.setToolTipText(org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jMainJS.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jLabel4.text")); // NOI18N
        jLabel4.setToolTipText(org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jThemeCSS.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jLabel5.text")); // NOI18N
        jLabel5.setToolTipText(org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jJQueryJS.toolTipText")); // NOI18N

        jTitleField.setText("Bootstrap Template"); // NOI18N
        jTitleField.setToolTipText(org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jTitleField.toolTipText")); // NOI18N

        jMainCSS.setText("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"); // NOI18N
        jMainCSS.setToolTipText(org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jMainCSS.toolTipText")); // NOI18N

        jJQueryJS.setText("https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"); // NOI18N
        jJQueryJS.setToolTipText(org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jJQueryJS.toolTipText")); // NOI18N

        jMainJS.setText("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"); // NOI18N
        jMainJS.setToolTipText(org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jMainJS.toolTipText")); // NOI18N

        jThemeCSS.setText("https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"); // NOI18N
        jThemeCSS.setToolTipText(org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jThemeCSS.toolTipText")); // NOI18N

        jSupportOldIE.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jSupportOldIE, org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jSupportOldIE.text")); // NOI18N
        jSupportOldIE.setToolTipText(org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jSupportOldIE.toolTipText")); // NOI18N

        jAddContainer.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jAddContainer, org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jAddContainer.text")); // NOI18N
        jAddContainer.setToolTipText(org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jAddContainer.toolTipText")); // NOI18N
        jAddContainer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jAddContainerItemStateChanged(evt);
            }
        });

        jContainerClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "container", "container-fluid" }));
        jContainerClass.setToolTipText(org.openide.util.NbBundle.getMessage(BlankPageCustomizer.class, "BlankPageCustomizer.jAddContainer.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAddContainer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jContainerClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTitleField)
                                    .addComponent(jMainCSS, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jJQueryJS)
                                    .addComponent(jMainJS, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                    .addComponent(jThemeCSS, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(jSupportOldIE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jMainCSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jJQueryJS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jMainJS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jThemeCSS)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addComponent(jSupportOldIE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jContainerClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddContainer))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jAddContainerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jAddContainerItemStateChanged
        jContainerClass.setEnabled(jAddContainer.isSelected());
    }//GEN-LAST:event_jAddContainerItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jAddContainer;
    private javax.swing.JComboBox<String> jContainerClass;
    private javax.swing.JTextField jJQueryJS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jMainCSS;
    private javax.swing.JTextField jMainJS;
    private javax.swing.JCheckBox jSupportOldIE;
    private javax.swing.JTextField jThemeCSS;
    private javax.swing.JTextField jTitleField;
    // End of variables declaration//GEN-END:variables
}
