/*
 * palette4bootstrap - A netbeans palette plugin for the Bootstrap
 * Copyright (c) 2017-2018 Tauquir Ahmed (tauquirahmed93@gmail.com)
 * Licensed under the MIT License.
 */
package org.tauquir.palette4bootstrap.items;

import java.awt.Dialog;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.openide.util.NbBundle;
import org.tauquir.palette4bootstrap.bsPaletteUtilities;

public class ImageCustomizer extends javax.swing.JPanel {

    private boolean dialogOK = false;
    private JDialog jd;
    private final Image image;
    private final JFileChooser imgChooser;
    private final String currentDirectory;

    /**
     * Creates new form ImageCustomizer
     */
    public ImageCustomizer(Image image, File currentFile) {
        this.image = image;
        initComponents();
        currentDirectory = currentFile.getParent();
        imgChooser = initFileChooser();
    }

    public boolean showDialog() {
        dialogOK = false;
        jd = new JDialog();
        jd.setSize(this.getPreferredSize());
        jd.setIconImage(new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB_PRE));
        jd.setTitle(NbBundle.getMessage(getClass(), "Customizer.InsertPrefix")
                + " " + NbBundle.getMessage(getClass(), "MEDIA.IMAGE.NAME"));
        jd.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        jd.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
        jd.add(this);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        jd.addWindowListener(new WindowAdapter() {
            @Override
            public void windowDeactivated(WindowEvent e) {
                /* Reset every parameter of image object so that old values
                   does not appear on re-opening the dialog */
                image.setSrc("http://via.placeholder.com/350x150");
                image.setAlt("");
                image.setHeight("");
                image.setWidth("");
                image.removeAllClasses();
            }
        });
        return dialogOK;
    }

    private JFileChooser initFileChooser() {
        JFileChooser chooser = new JFileChooser();
        chooser.setApproveButtonText(NbBundle.getMessage(getClass(), "ImageCustomizer.FileChooser.ApproveButtonText"));
        chooser.setCurrentDirectory(new File(currentDirectory));
        chooser.setDialogTitle(NbBundle.getMessage(getClass(), "ImageCustomizer.FileChooser.Title"));
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg", "bmp", "svg", "ico"));
        return chooser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dialogCancelBtn = new javax.swing.JButton();
        dialogOKBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        codeGenerated = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        srcTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        altTextField = new javax.swing.JTextField();
        widthTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        heightTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        shapeSelector = new javax.swing.JComboBox<>();
        responsiveCheckBox = new javax.swing.JCheckBox();
        openFileChooserButton = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.BorderLayout());

        org.openide.awt.Mnemonics.setLocalizedText(dialogCancelBtn, org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "Customizer.Cancel")); // NOI18N
        dialogCancelBtn.setMaximumSize(new java.awt.Dimension(69, 23));
        dialogCancelBtn.setMinimumSize(new java.awt.Dimension(69, 23));
        dialogCancelBtn.setPreferredSize(new java.awt.Dimension(69, 23));
        dialogCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dialogCancelBtn, java.awt.BorderLayout.EAST);

        org.openide.awt.Mnemonics.setLocalizedText(dialogOKBtn, org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "Customizer.OK")); // NOI18N
        dialogOKBtn.setMaximumSize(new java.awt.Dimension(69, 23));
        dialogOKBtn.setMinimumSize(new java.awt.Dimension(69, 23));
        dialogOKBtn.setPreferredSize(new java.awt.Dimension(69, 23));
        dialogOKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dialogOKBtn, java.awt.BorderLayout.WEST);

        codeGenerated.setEditable(false);
        codeGenerated.setColumns(20);
        codeGenerated.setRows(5);
        codeGenerated.setText("<img src=\"http://via.placeholder.com/350x150\"/>"); // NOI18N
        codeGenerated.setWrapStyleWord(true);
        codeGenerated.setFocusable(false);
        jScrollPane1.setViewportView(codeGenerated);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "Customizer.GeneratedCode")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.jLabel3.text")); // NOI18N
        jLabel3.setToolTipText(org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.srcTextField.toolTipText")); // NOI18N

        srcTextField.setText("http://via.placeholder.com/350x150"); // NOI18N
        srcTextField.setToolTipText(org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.srcTextField.toolTipText")); // NOI18N
        srcTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                srcTextFieldFocusLost(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.jLabel4.text")); // NOI18N
        jLabel4.setToolTipText(org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.altTextField.toolTipText")); // NOI18N

        altTextField.setToolTipText(org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.altTextField.toolTipText")); // NOI18N
        altTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                altTextFieldFocusLost(evt);
            }
        });

        widthTextField.setToolTipText(org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.widthTextField.toolTipText")); // NOI18N
        widthTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                widthTextFieldFocusLost(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.jLabel5.text")); // NOI18N
        jLabel5.setToolTipText(org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.widthTextField.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.jLabel6.text")); // NOI18N
        jLabel6.setToolTipText(org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.heightTextField.toolTipText")); // NOI18N

        heightTextField.setToolTipText(org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.heightTextField.toolTipText")); // NOI18N
        heightTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                heightTextFieldFocusLost(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.jLabel7.text")); // NOI18N
        jLabel7.setToolTipText(org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.shapeSelector.toolTipText")); // NOI18N

        shapeSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "img-thumbnail", "img-circle", "img-rounded" }));
        shapeSelector.setToolTipText(org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.shapeSelector.toolTipText")); // NOI18N
        shapeSelector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shapeSelectorItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(responsiveCheckBox, org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.responsiveCheckBox.text")); // NOI18N
        responsiveCheckBox.setToolTipText(org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "ImageCustomizer.responsiveCheckBox.toolTipText")); // NOI18N
        responsiveCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                responsiveCheckBoxItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(openFileChooserButton, org.openide.util.NbBundle.getMessage(ImageCustomizer.class, "Customizer.Browse")); // NOI18N
        openFileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileChooserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(altTextField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(shapeSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(widthTextField))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(heightTextField))
                                    .addComponent(responsiveCheckBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(srcTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openFileChooserButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(srcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openFileChooserButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(altTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(shapeSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(responsiveCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dialogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogBtnActionPerformed
        javax.swing.JButton button = (javax.swing.JButton) evt.getSource();
        if (button.equals(dialogOKBtn)) {
            dialogOK = true;
            jd.dispose();

        } else if (button.equals(dialogCancelBtn)) {
            dialogOK = false;
            jd.dispose();
        }
    }//GEN-LAST:event_dialogBtnActionPerformed

    private void srcTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_srcTextFieldFocusLost
        image.setSrc(srcTextField.getText());
        codeGenerated.setText(image.generateBody());
    }//GEN-LAST:event_srcTextFieldFocusLost

    private void altTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_altTextFieldFocusLost
        image.setAlt(altTextField.getText());
        codeGenerated.setText(image.generateBody());
    }//GEN-LAST:event_altTextFieldFocusLost

    private void widthTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_widthTextFieldFocusLost
        image.setWidth(widthTextField.getText());
        codeGenerated.setText(image.generateBody());
    }//GEN-LAST:event_widthTextFieldFocusLost

    private void heightTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_heightTextFieldFocusLost
        image.setHeight(heightTextField.getText());
        codeGenerated.setText(image.generateBody());
    }//GEN-LAST:event_heightTextFieldFocusLost

    private void responsiveCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_responsiveCheckBoxItemStateChanged
        if (responsiveCheckBox.isSelected()) {
            image.addClass("img-responsive");
        } else {
            image.removeClass("img-responsive");
        }
        codeGenerated.setText(image.generateBody());
    }//GEN-LAST:event_responsiveCheckBoxItemStateChanged

    private void shapeSelectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shapeSelectorItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            if (!evt.getItem().equals("Normal")) {             // if "Normal" option was not selected
                image.addClass(evt.getItem().toString());
                codeGenerated.setText(image.generateBody());
            }
        } else if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) {
            image.removeClass(evt.getItem().toString());  // Remove the deselected item from the list
            codeGenerated.setText(image.generateBody());
        }
    }//GEN-LAST:event_shapeSelectorItemStateChanged

    private void openFileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileChooserButtonActionPerformed
        int v = imgChooser.showOpenDialog(this);
        if (v == JFileChooser.APPROVE_OPTION) {
            File file = imgChooser.getSelectedFile();
            String relativePath = bsPaletteUtilities.findRelativePath(file.getAbsolutePath(), currentDirectory);
            srcTextField.setText(relativePath);
            image.setSrc(relativePath);
            codeGenerated.setText(image.generateBody());
        }
    }//GEN-LAST:event_openFileChooserButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altTextField;
    private javax.swing.JTextArea codeGenerated;
    private javax.swing.JButton dialogCancelBtn;
    private javax.swing.JButton dialogOKBtn;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openFileChooserButton;
    private javax.swing.JCheckBox responsiveCheckBox;
    private javax.swing.JComboBox<String> shapeSelector;
    private javax.swing.JTextField srcTextField;
    private javax.swing.JTextField widthTextField;
    // End of variables declaration//GEN-END:variables
}
